footer:
  social_links:
  - name: YouTube
    url: https://www.youtube.com
    icon: youtube
  - name: Instagram
    url: https://www.instagram.com
    icon: instagram
  - name: Facebook
    url: https://www.facebook.com
    icon: facebook
  logo:
    src: https://dummyimage.com/120x40/ffffff/333333&text=LOGO
    alt: 範例LOGO
login_ua:
  agreement_text: 登入即表示您同意我們的
  terms_link: /service_term
  terms_text: 服務條款
  and_text: 和
  privacy_link: /privacy_policy
  privacy_text: 隱私政策
login_title:
  heading: 透過 Patreon 登入，自動載入會籍
  description_line1: 根據您的會籍決定每個月可以生成幾次Streamlit應用。
  description_line2: 每位新用戶可每月免費體驗一次生成服務。
privacy_policy:
  title: 隱私政策
  last_updated: 最後更新日期：2024年12月4日
  sections:
    introduction:
      title: 1. 引言
      content: 歡迎使用檢測patreon訂閱狀態服務。本隱私政策旨在說明我們如何收集、使用、披露和保護您的個人信息。
    data_collection:
      title: 2. 信息收集
      intro: 我們可能收集以下類型的信息：
      list_items:
      - 個人識別信息（如姓名、電子郵件地址）
      - Patreon 帳戶信息（用於確認訂閱狀態）
      - 使用數據（如訪問日誌、IP地址）
    data_usage:
      title: 3. 信息使用
      intro: 我們使用收集的信息來：
      list_items:
      - 提供、維護和改進我們的服務
      - 處理訂閱和付款
      - 發送服務相關通知
    data_sharing:
      title: 4. 信息共享
      intro: 我們不會出售您的個人信息。我們可能在以下情況下共享信息：
      list_items:
      - 經您同意
      - 遵守法律要求
      - 與服務提供商合作（如 Patreon）
    data_security:
      title: 5. 數據安全
      content: 我們採取合理措施保護您的信息，但不能保證絕對安全。
    user_rights:
      title: 6. 您的權利
      content: 您有權訪問、更正或刪除您的個人信息。
    changes:
      title: 7. 變更
      content: 我們可能會不時更新本隱私政策。重大變更將通過電子郵件或網站通知。
    contact:
      title: 8. 聯繫我們
      content: 如有任何問題，請聯繫：example@gmail.com
  return_button:
    link: /app
    text: 返回登入
service_term:
  title: 服務條款
  last_updated: 最後更新日期：2024年12月4日
  sections:
    acceptance:
      title: 1. 接受條款
      content: 使用檢測patreon訂閱狀態服務即表示您同意這些條款。如果您不同意，請勿使用本服務。
    description:
      title: 2. 服務描述
      content: 我們提供基於 Streamlit 的網站服務，根據 Patreon 訂閱狀態提供不同等級的功能。
    account:
      title: 3. 用戶帳戶
      content: 您需要創建帳戶並連接 Patreon 以使用某些功能。您負責維護帳戶安全。
    subscription:
      title: 4. 訂閱和付款
      content: 訂閱和付款通過 Patreon 處理。退款和取消政策遵循 Patreon 的規定。
    behavior:
      title: 5. 用戶行為
      intro: 您同意不會：
      list_items:
      - 違反任何法律
      - 侵犯他人權利
      - 干擾服務運行
    intellectual_property:
      title: 6. 知識產權
      content: 服務內容受版權保護。您不得未經授權使用。
    disclaimer:
      title: 7. 免責聲明
      content: 服務"按原樣"提供，不提供任何明示或暗示的保證。
    limitation:
      title: 8. 責任限制
      content: 在法律允許的最大範圍內，我們不對任何損失負責。
    modification:
      title: 9. 修改服務
      content: 我們保留隨時修改或終止服務的權利。
    contact:
      title: 10. 聯繫我們
      content: 如有任何問題，請聯繫：example@gmail.com
  return_button:
    link: /app
    text: 返回登入
navbar:
  logo:
    link: /
    image_path: https://dummyimage.com/120x40/ffffff/333333&text=LOGO
    alt_text: 範例LOGO
    height: '40'
  toggle_button:
    title: Navigation Toggle
  menu_items:
  - type: link
    link: /
    text: 首頁
  - type: dropdown
    link: '#'
    text: 會籍資訊
    dropdown_content:
    - label: 層級
      value_var: '{{ level }}'
    - label: 金額
      value_var: '{{ amount }}'
    - label: 狀態
      value_var: '{{ status }}'
    - label: 加入日期
      value_var: '{{ date }}'
