footer:
  social_links:
  - name: YouTube
    url: https://www.youtube.com
    icon: youtube
  - name: Instagram
    url: https://www.instagram.com
    icon: instagram
  - name: Facebook
    url: https://www.facebook.com
    icon: facebook
  logo:
    src: https://dummyimage.com/120x40/ffffff/333333&text=LOGO
    alt: example logo
