landing:
  navbar:
    logo:
      link: /
      image_path: https://dummyimage.com/120x40/ffffff/333333&text=LOGO
      alt_text: "[Your Company Name]"
      height: '20'
    toggle_button:
      title: Toggle Navigation
    left_menu_items:
    - link: '#home'
      text: "[Menu Item 1]"
    - link: '#feature'
      text: "[Menu Item 2]"
    - link: '#demo'
      text: "[Menu Item 3]"
    - link: '#pricing'
      text: "[Menu Item 4]"
    cta_button:
      link: /app
      icon: bi bi-magic
      text: "[CTA Button]"
      class: btn btn-primary
  hero:
    section_id: home
    video:
      source: app/static/Placeholder_Video.mp4
      type: video/mp4
    heading: Concise headline describing your product's<br><span class="text-primary">core value</span>
    subtitle: "Descriptive content explaining what your product is."
    cta_button:
      link: /app
      text: "[Primary CTA Button]"
      icon: bi bi-chevron-right
      class: btn btn-primary btn-lg
  feature:
    section_id: feature
    title: "[Feature Highlights Title]"
    subtitle: "[Feature highlights subtitle description]"
    list_item:
    - column_width: '7'
      icon_url: https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.0/icons/lightning-charge.svg
      icon_alt: Lightning Fast Performance
      title: "[Lightning Fast]"
      description: "[Describe your first core feature here, explaining how it brings value to users...]"
    - column_width: '5'
      icon_url: https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.0/icons/shield-check.svg
      icon_alt: Security Protection
      title: "[Security Protection]"
      description: "[Describe your second core feature here, highlighting its unique advantages...]"
    - column_width: '4'
      icon_url: https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.0/icons/gear.svg
      icon_alt: Easy Configuration
      title: "[Easy Setup]"
      description: "[Describe your third feature here, showcasing technical advantages...]"
    - column_width: '4'
      icon_url: https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.0/icons/people.svg
      icon_alt: Team Collaboration
      title: "[Team Collaboration]"
      description: "[Describe your fourth feature here, emphasizing security or convenience...]"
    - column_width: '4'
      icon_url: https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.0/icons/graph-up.svg
      icon_alt: Analytics Dashboard
      title: "[Data Analytics]"
      description: "[Describe your fifth feature here, explaining business value...]"
  demo:
    section_id: demo
    heading: "[Product Demo Title]<br>[Subtitle Description]"
    image:
      src: https://dummyimage.com/800x600/cccccc/333333&text=Replace+Demo+Image
      height: '1028'
      width: '2168'
      alt: "Product demo image"
    main_title: "[Place your main product description here, describing your core value proposition!]"
    benefits:
    - icon_class: bi bi-cpu
      title: "[Smart Processing]"
      description: "[Describe your product's first major advantage or feature]"
    - icon_class: bi bi-rocket-takeoff
      title: "[Rapid Deployment]"
      description: "[Describe your product's second major advantage or feature]"
    - icon_class: bi bi-shield-lock
      title: "[Secure & Reliable]"
      description: "[Describe your product's third major advantage or feature]"
    cta_buttons:
    - class: btn btn-primary btn-lg me-3
      link: /app
      text: "[Primary Action Button]"
      icon: bi bi-play-circle
    - class: btn btn-outline-primary btn-lg
      link: /app
      text: "[Secondary Action Button]"
      icon: bi bi-info-circle
  pricing:
    section_id: pricing
    title: "[Choose Your Plan]"
    feature_icon: bi bi-check-circle
    plans:
    - name: "[Free Plan]"
      is_popular: false
      price: "$0"
      price_period: "/month"
      ai_quota: "[Plan limitation description]"
      features:
      - "[Feature item 1]"
      - "[Feature item 2]"
      - "[Feature item 3]"
      button:
        link: "#"
        class: btn btn-outline-primary w-100
        text: "[Get Started Free]"
        icon: bi bi-download
    - name: "[Basic Plan]"
      is_popular: true
      price: "$[Price]"
      price_period: "/month"
      ai_quota: "[Plan limitation description]"
      features:
      - "[Feature item 1]"
      - "[Feature item 2]"
      - "[Feature item 3]"
      - "[Feature item 4]"
      button:
        link: "#"
        class: btn btn-primary w-100
        text: "[Upgrade Now]"
        icon: bi bi-arrow-up-circle
      popular_badge_text: "Most Popular"
      popular_badge_class: badge bg-success
    - name: "[Premium Plan]"
      is_popular: false
      price: "$[Price]"
      price_period: "/month"
      ai_quota: "[Plan limitation description]"
      features:
      - "[Feature item 1]"
      - "[Feature item 2]"
      - "[Feature item 3]"
      - "[Feature item 4]"
      - "[Feature item 5]"
      button:
        link: "#"
        class: btn btn-outline-primary w-100
        text: "[Upgrade Now]"
        icon: bi bi-star
  faq:
    title: "[Frequently Asked Questions]"
    faq_items:
    - question: "[Question 1: Basic question about the product?]"
      answer: "[Answer the first most common question users ask, providing clear and detailed explanation...]"
    - question: "[Question 2: Technical or usage-related question?]"
      answer: "[Answer technical questions here, helping users understand the product's technical advantages...]"
    - question: "[Question 3: Pricing or business model question?]"
      answer: "[Explain pricing strategy and business model here, helping users understand the value proposition...]"
    - question: "[Question 4: Support or service-related question?]"
      answer: "[Explain customer support and service content here, building user confidence...]"
